- name: Run chart-releaser
  uses: helm/chart-releaser-action@v1.2.0
  with:
    charts_dir: charts
    config: cr.yaml
    charts_repo_url: https://github.com/khush-deep14/my-helm-charts
  env:
    CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
